### ISSUE TITLE
Read me example error

### ISSUE THREAD

**Issue by Stevec4** [peterkahl/TimeZoneCity#2]
Hi Peter 
Thanks for the making these available. I have been playing around with them and in your example in the read me I get an error.
This line throws and error.
echo '>(UTC'. $val['std_offset_formatted'] .') '. $place .'</option>'."\n";

If I change 'std_offset_formatted' to 'std_offset' it works fine.

Steve

**Comment by peterkahl** [comment]
@Stevec4 Thank you for pointing that out.
Which line do you speak of? Is it somewhere in the usage examples in README.md?

In such case, the right key should be `'offset_formatted'`. Can you try it?

**Comment by Stevec4** [comment]
Peter
It was in ver 6 of the readme around line 187 & 206.  
I see you updated to ver 7.1 and it is fix. 
Steve
